# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actionson push

name: Update Charts

on:
  workflow_dispatch: # Put here!!
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up Git credentials
      run: |
        git config --global user.email "ch.dhainaut@gmail.com"
        git config --global user.name "Automated Updater"
    - name: Git pull
      run: |
        git pull
    - name: Generate Charts
      run: |
        python main.py
    - name: Commit back to the repo to update
      run: |
        git add .
        git commit -m "Automated monthly update"
        git push
